### ISSUE TITLE
[버그] 홍콩 MTR 차량 등장시기 정리

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#10]
==========[버그내용]==========
홍콩 MTR 전동차는 실제 차량의 등장시기와 상관없이 모두 1979년 등장으로 되어있음

==========[개선사항]==========
아래 내용대로 등장년도 수정을 부탁드립니다.
CTS에서 아직 추가되지 않은 차량들을 추가할 때 에도 아래 표를 참고해주십시오.

| 이름 | 등장년도 |
|--------|--------|
|AD Tranz CAF A형|1996년|
|메트로카멜 교류형|1980년|
|메트로카멜 직류형|1977년|
|CNR 창춘|2010년|
|CNR CRRC|2015년|
|현대로템 미쓰비시|2002년|
|현대로템 R형|2014년|
|IKK SP 1900|1999년|

+ `현대로템 미쓰비시`는 등장년도 시기 상 `로템 미쓰비시`로 바꾸는게 정확할 듯 합니다.

==========[YST내용]==========
DTS 열차 이름 : 상단 표 참고

raf.
https://namu.wiki/w/MTR%20Adtranz-CAF%20%EC%A0%84%EB%8F%99%EC%B0%A8

https://namu.wiki/w/MTR%20%EB%A9%94%ED%8A%B8%EB%A1%9C%EC%B9%B4%EB%A9%9C%20%EA%B5%90%EB%A5%98%ED%98%95%20%EC%A0%84%EB%8F%99%EC%B0%A8

https://namu.wiki/w/MTR%20%EB%A9%94%ED%8A%B8%EB%A1%9C%EC%B9%B4%EB%A9%9C%20%EC%A7%81%EB%A5%98%ED%98%95%20%EC%A0%84%EB%8F%99%EC%B0%A8

https://namu.wiki/w/MTR%20CNR-%EC%B0%BD%EC%B6%98%20%EC%A0%84%EB%8F%99%EC%B0%A8

https://namu.wiki/w/MTR%20CRRC%20%EC%B0%BD%EC%B6%98%20%EC%A0%84%EB%8F%99%EC%B0%A8

https://namu.wiki/w/MTR%20%EB%A1%9C%ED%85%9C-%EB%AF%B8%EC%93%B0%EB%B9%84%EC%8B%9C%20%EC%A0%84%EB%8F%99%EC%B0%A8

https://namu.wiki/w/MTR%20%ED%98%84%EB%8C%80%EB%A1%9C%ED%85%9C%20R%ED%98%95%20%EC%A0%84%EB%8F%99%EC%B0%A8

https://namu.wiki/w/IKK%20SP1900%ED%98%95%20%EC%A0%84%EB%8F%99%EC%B0%A8

**Comment by evepoi** [comment]
해당자료는 자료 정리로 인해 MTR이 제외되면서 보류되었습니다.
