### ISSUE TITLE
[열차추가] 한큐전철 9000계 전동차

### ISSUE THREAD

**Issue by kimjostars** [DTS-NewGRF/DTS#109]
==========[필수스프라이트]==========
![Hankyu-9000,9300](https://github.com/DTS-NewGRF/DTS/assets/110330835/27ebdbb7-883a-4bc8-b23d-1cc6e79115fa)

==========[설명]==========
한큐전철의 신포선용 전동차입니다.

==========[적용스팩]==========
GRF내 열차 이름 : 한큐전철 9000계/Hankyu 9000series
열차속도 : 120km/h
도입년도 : 2010년
객차당 수송량 : 량당131명
최소 편성수 : 8량
실존여부 : O
==========[편성구조]==========
앞- N량 객차 - 뒤 순으로 편성 명시.
Mc' - M,T - M,T - M,T - M,T - M,T -M,T' - Mc

**Comment by JukjeonWani** [comment]
- [ ] 출발 사운드 작업 완료 시 체크
