### ISSUE TITLE
[열차변경] 8600호대 전기기관차 리메이크

### ISSUE THREAD

**Issue by kimjostars** [DTS-NewGRF/DTS#142]
### 기본 열차 선택

[DTS/단량] 8600호대 전기기관차

### 변경 스프라이트

![EL-8600](https://github.com/DTS-NewGRF/DTS/assets/110330835/f4c04e99-e3c4-44da-94d8-62812ed2b529)

### 설명

기존그래픽이 7000호대 전기기관차와 비슷하고 타 전기기관차와 단랑인점이 유사하여 콘셉트을 변경합니다.

출력및 견인력은 단량은 현행유지 1량식 늘때마다 50%식 증가

### 적용내용

그래픽 변경 편성변경

### 편성구조

단량에서 1~4량으로 변경 

단량 A'
2량 A'-B
3량 A'-B-B'
4량 A'-B-B'-A

**Comment by JukjeonWani** [comment]
- [ ] FEL8500Start
출발 사운드 적용

- 편성이 늘어날수록 출력도 6,600kw씩 증가
