### ISSUE TITLE
[열차추가] HYEL-15

### ISSUE THREAD

**Issue by kimjostars** [DTS-NewGRF/DTS#15]
==========[필수스프라이트]==========
![HYEL-15](https://github.com/DTS-NewGRF/DTS/assets/110330835/ac618f1c-36de-426e-9b7a-5c2b69d9c800)

==========[설명]==========
항구나 조차장,공장내부 에서 쓰일법한 수소전지기관차의 2CC도색

==========[적용스팩]==========
GRF내 열차 이름 : HYEL-15
도입년도 : 타수소열차와 동일
객차당 수송량 : 0
실존여부 : X

**Comment by JukjeonWani** [comment]
이름추천: HYEL-15
(본선용 영업 차량이 아님을 고려, 두자릿수 숫자 부여)

**Comment by kimjostars** [comment]
> 이름추천: HYEL -15

Good!
