### ISSUE TITLE
[열차추가] TGV POS

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#19]
==========[필수스프라이트]==========
· 아틀란틱 블루 도색
![TGV_POS](https://github.com/DTS-NewGRF/DTS/assets/88026704/ae57feea-89c1-4315-ae97-66afa585cc53)
· 현 도색(카밀론 도색)
![TGV_POS_Carmillon](https://github.com/DTS-NewGRF/DTS/assets/88026704/e13f31ef-9216-46d8-9c84-000569daa457)
· 리리아
![TGV_POS_Lyria](https://github.com/DTS-NewGRF/DTS/assets/88026704/ca73d451-996c-4609-b06b-adba34bda4b1)
· 탈리스 PBKA
![TGV_POS_Thalys](https://github.com/DTS-NewGRF/DTS/assets/88026704/8464f386-bd97-4335-98ad-3fabe5fb2cec)

==========[설명]==========
TGV POS의 초기도색, 카밀론 도색, 리리아 도색, 탈리스 도색입니다.

==========[기본GRF]==========
베이스 : ETS
도색 : 초기도색, 카밀론, 리리아, 탈리스

==========[적용스팩]==========
GRF내 열차 이름 : TGV POS
열차속도 : 320km/h
도입년도 : 1996(탈리스 PBKA), 2006(TGV POS) 
객차당 수송량 : 1등석 1량 당 40명, 2등석 1량 당 64명, 식당차 10명
최소 편성수 : 4
실존여부 : 실존

**Comment by evepoi** [comment]
통합 작업으로 포함되었습니다.
