### ISSUE TITLE
[열차추가] TGV Duplex

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#20]
==========[필수스프라이트]==========
· 아틀란틱 블루 도색
![TGV_Duplex](https://github.com/DTS-NewGRF/DTS/assets/88026704/4f8df9c0-dc0f-4f3c-a6e2-479a7aa42f83)
· 리리아 도색
![TGV_Duplex_Lyria](https://github.com/DTS-NewGRF/DTS/assets/88026704/d3235302-0496-460c-8a32-d136aa8980fc)
· OUIGO
![TGV_Duplex_Ouigo](https://github.com/DTS-NewGRF/DTS/assets/88026704/8b26b51f-4644-45c2-8f24-a4e35db1830f)

==========[설명]==========
TGV 듀플렉스의 도색들입니다.

==========[기본GRF]==========
베이스 : ETS
도색 : 아틀란틱 블루, 리리아, 카밀론, OUIGO

==========[적용스팩]==========
GRF내 열차 이름 : 테제베 듀플렉스 / TGV Duplex
열차속도 : 320km/h
도입년도 : 1996
객차당 수송량 :
| 이름 | 수송량 | 비고 |
|-----|-----|-----|
| TGV 듀플렉스 | 1등석 56명, 2등석 85명, 식당차 10명 | |
| TGV OUIGO | 2등석 85명, 식당차 39명 | 식당차 설비를 들어내고 좌석을 설치함 |

최소 편성수 : 4
실존여부 : 실존

**Comment by evepoi** [comment]
통합 작업으로 추가되었습니다.
