### ISSUE TITLE
[버그] [중대사항] 서울교통공사 2세대 4000호대 전동차 그래픽이 바뀌었습니다!

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#203]
### 기본 열차 선택

[DTS] 서울교통공사 2세대 VVVF 전동차

### 버그사항

![image](https://github.com/DTS-NewGRF/DTS/assets/88026704/c01bc56b-1433-4ba9-a7cb-ebf58af066ac)
서울교통공사 2세대 4000호대 전동차 GTO의 그래픽이 서울교통공사 2세대 3000호대 전동차 그래픽으로 보이는 현상이 발생하였습니다.

### 개선점

사운드 및 구매창 이미지에는 문제 없음, 실제 구매하면 보이는 스프라이트가 잘못 적용된 것으로 보입니다.

확인 결과 뒤집힘 방지를 적용하면서 그래픽이 잘못 적용된 것으로 보입니다.

**Comment by evepoi** [comment]
이미지 적용이 뒤집힌 세팅에 3000호대로 잡혀있네요. 작업시 수정하겠습니다.

**Comment by JukjeonWani** [comment]
> 이미지 적용이 뒤집힌 세팅에 3000호대로 잡혀있네요. 작업시 수정하겠습니다.

그래픽 스프라이트에는 문제가 없습니다. 
(위 그래픽 스프라이트를 사용함) https://github.com/DTS-NewGRF/DTS/blob/minengallery/src/metro/VVVF/Seoulmetro_2nd/Seoulmetro_2nd_4000.png
코딩 과정에서 실수가 있었던 것 같습니다.
