### ISSUE TITLE
[열차추가] NSW TrainLink D set

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#21]
==========[필수스프라이트]==========
![image](https://github.com/DTS-NewGRF/DTS/assets/88026704/739112ad-0dce-427b-b14c-67ce4bdafc71)

**편성도**
![image](https://github.com/DTS-NewGRF/DTS/assets/88026704/270af9b5-043a-4ad9-be54-d81568023bb6)

==========[설명]==========
해당 차량은 현대로템에서 제작한 호주수출열차로, 2019년부터 납품이 시작되었으며 2021년이나 2020년 말에 상업운행을 시작할 것이었던 것으로 보입니다, 코로나 19로 인해 2022년으로 운행개시가 늦춰졌다고는 하지만 이미 국내외에 관련자료가 많이 있어 한번 만들어봤습니다.

위에 올린 편성도대로 편성되는 차량이며, 4+4로 중련하여 8량으로 운행하거나 6+4로 중련하여 10량으로 운행할 것으로 보입니다. 현지 시운전 사진과 관련 문서의 서술로 보아 이는 확실한 것 같습니다.

==========[기본GRF]==========
베이스 : WTS

==========[적용스팩]==========
| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) _(예시. ``KTX 산천``)_ | NSW 트레인링크 D 세트 |
| 영문 이름(Name in English) _(예시. ``KTX Sancheon``)_ | NSW TrainLink D set |
| 코드(Code) _(예시. ``KTX2N``)_ | ``NTL_D`` |
| 운영 속력(Speed) _(예시. ``300km/h``)_ | 160 km/h |
| 설계 최고 속력(Designed max. speed) _(예시. ``330km/h``)_ | 160 km/h |
| 화물 수송량(Capacity) _(예시. ``100명``)_ | 운전차량: 130명, 객차: 134명 |
| 출력(Power) _(예시. ``4400kW``)_ | 8000kW |
| 중량(Weight) _(예시. ``136t``)_ | 60t |
| 도입연도(Introduction year) _(예시. ``2004``)_ | 2019 |
| 실존여부 | ○ |

**Comment by evepoi** [comment]
통합 작업으로 포함되었습니다.
