### ISSUE TITLE
[열차추가] 니시테츠 전동차

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#22]
==========[필수스프라이트]==========
* 니시테츠 1000형
![Nishitetsu_1000](https://github.com/DTS-NewGRF/DTS/assets/88026704/fe5581de-cfec-47b0-b32e-6d046ade84e6)
* 니시테츠 2000형
![Nishitetsu_2000](https://github.com/DTS-NewGRF/DTS/assets/88026704/185706ce-4297-4d00-ab44-119706dbad00)
* 니시테츠 3000형
![Nishitetsu_3000](https://github.com/DTS-NewGRF/DTS/assets/88026704/9e7edf83-4f54-40ac-831c-4a628f8d718a)
* 니시테츠 5000형
![Nishitetsu_5000](https://github.com/DTS-NewGRF/DTS/assets/88026704/3f74c238-b07b-404b-b5d5-26fa60c7229f)
* 니시테츠 6000형 / 6050형
![Nishitetsu_6000](https://github.com/DTS-NewGRF/DTS/assets/88026704/2c026cc3-ed7d-4939-a0fa-d9896148f5bc)
![Nishitetsu_6050](https://github.com/DTS-NewGRF/DTS/assets/88026704/8f74a60b-69ad-4028-9702-8e50283f769f)
* 니시테츠 7000형 / 7050형
![Nishitetsu_7000](https://github.com/DTS-NewGRF/DTS/assets/88026704/187689fa-f2a1-407f-bf90-c79a57df2a22)
![Nishitetsu_7050](https://github.com/DTS-NewGRF/DTS/assets/88026704/ae061740-b273-4ed4-a4f6-146b61e2e176)
* 니시테츠 8000형
![Nishitetsu_8000](https://github.com/DTS-NewGRF/DTS/assets/88026704/8b66f369-d7e4-48d2-8057-d36c3fd49f2b)
* 니시테츠 9000형
![Nishitetsu_9000_remake](https://github.com/DTS-NewGRF/DTS/assets/88026704/8fd5e8cf-d6cf-4687-b731-0b1e0e6d06f7)

==========[설명]==========
일본 사철인 니시테츠(서일본 철도) 전동차들입니다.

==========[기본GRF]==========
베이스 : JTS+
도색 : 실존했거나 실존하는 모든 도색

==========[적용스팩]==========
* 니시테츠 1000형

| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) _(예시. ``KTX 산천``)_ | 니시테츠 1000형 |
| 영문 이름(Name in English) _(예시. ``KTX Sancheon``)_ | Nishitetsu 1000 series |
| 코드(Code) _(예시. ``KTX2N``)_ | ``Nishitetsu_1000`` |
| 운영 속력(Speed) _(예시. ``300km/h``)_ | 110 km/h |
| 설계 최고 속력(Designed max. speed) _(예시. ``330km/h``)_ | 110 km/h |
| 화물 수송량(Capacity) _(예시. ``100명``)_ | ``선두차 140명`` ``중간차 150명`` |
| 출력(Power) _(예시. ``4400kW``)_ | 640kW |
| 중량(Weight) _(예시. ``136t``)_ | 34t |
| 도입연도(Introduction year) _(예시. ``2004``)_ | 1957 |

| 도색 이름 | 등장 년도 | 특징 |
| -------- | --------- | --------- |
| 초기 도색 | 1957 | 등장시 도색 |
| 특급 도색 | 1959 | 특급 격상 |
| 일반 도색 | 1973 | 출입문 3개로 증설, 급행 격하 |
| 냉방개조 | 1982 | 에어컨 설치, 보통 격하 |
| 특별 도색 | 2001 | 퇴역 전 이벤트 도색 |

조성 ``TC - M' - M' - TC``

-----

*  니시테츠 2000형

| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) _(예시. ``KTX 산천``)_ | 니시테츠 2000형 |
| 영문 이름(Name in English) _(예시. ``KTX Sancheon``)_ | Nishitetsu 2000 series |
| 코드(Code) _(예시. ``KTX2N``)_ | ``Nishitetsu_2000`` |
| 운영 속력(Speed) _(예시. ``300km/h``)_ | 110 km/h |
| 설계 최고 속력(Designed max. speed) _(예시. ``330km/h``)_ | 110 km/h |
| 화물 수송량(Capacity) _(예시. ``100명``)_ | ``선두차 123명`` ``객차 134명`` |
| 출력(Power) _(예시. ``4400kW``)_ | 2,160kW |
| 중량(Weight) _(예시. ``136t``)_ | ``선두차 30t`` ``객차 35t`` |
| 도입연도(Introduction year) _(예시. ``2004``)_ | 1973 |

| 도색 이름 | 등장년도 | 특징 |
| --------- | --------- | --------- |
| 특급 | 1973 | 등장시 도색, 2Door |
| 일반 도색 | 1989 | 출입문 3개로 증설, 급행 격하 |

``TC - M - M' - M - M' - TC`` 6량 한편성

-----

* 니시테츠 3000형

| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) _(예시. ``KTX 산천``)_ | 니시테츠 3000형 |
| 영문 이름(Name in English) _(예시. ``KTX Sancheon``)_ | Nishitetsu 3000 series |
| 코드(Code) _(예시. ``KTX2N``)_ | ``Nishitetsu_3000`` |
| 운영 속력(Speed) _(예시. ``300km/h``)_ | 110 km/h |
| 설계 최고 속력(Designed max. speed) _(예시. ``330km/h``)_ | 120 km/h |
| 화물 수송량(Capacity) _(예시. ``100명``)_ | ``선두차: 118명`` ``중간차: 131명`` |
| 출력(Power) _(예시. ``4400kW``)_ | ``2량 175kw×3개=525kw`` ``3량 175kw×4개=700kw`` ``5량 175kw×7개=1225kw`` |
| 중량(Weight) _(예시. ``136t``)_ | ``선두차: 28t`` ``중간차 36t`` |
| 도입연도(Introduction year) _(예시. ``2004``)_ | 2005 |

2량 ``MC' - TC``
3량 ``TC - M' - TC``
5량 ``TC - M' - T - M' - TC``
팬터그래프 없는 객차 스트라이프는 5량열차에만 사용됩니다.

-----

* 니시테츠 5000형

| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) _(예시. ``KTX 산천``)_ | 니시테츠 5000형 |
| 영문 이름(Name in English) _(예시. ``KTX Sancheon``)_ | Nishitetsu 5000 series |
| 코드(Code) _(예시. ``KTX2N``)_ | ``Nishitetsu_5000`` |
| 운영 속력(Speed) _(예시. ``300km/h``)_ | 110 km/h |
| 설계 최고 속력(Designed max. speed) _(예시. ``330km/h``)_ | 120 km/h |
| 화물 수송량(Capacity) _(예시. ``100명``)_ | ``선두차 140명`` ``중간차 150명`` |
| 출력(Power) _(예시. ``4400kW``)_ | 1,080kW(``3량`` ``4량``) |
| 중량(Weight) _(예시. ``136t``)_ | ``선두차 28t`` ``객차 36t`` |
| 도입연도(Introduction year) _(예시. ``2004``)_ | 1975 |

3량 ``MC - M' - TC``
4량 ``TC - M - M' - TC`` ``(MC - M' - T - TC (3량 → 4량 증량 한정))``

* MG(전동발전기) 사용 차량은 팬터그래프 1개
* SIV(정지형 인버터) 사용 차량은 팬터그래프 2개 입니다.

팬터그래프 없는 중간객차 스프라이트는 4량열차에서만 사용합니다.

-----

* 니시테츠 6000형 / 6050형

| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) _(예시. ``KTX 산천``)_ | 니시테츠 6000/6050형 |
| 영문 이름(Name in English) _(예시. ``KTX Sancheon``)_ | Nishitetsu 6000/6050 series |
| 코드(Code) _(예시. ``KTX2N``)_ | ``Nishitetsu_6000`` ``Nishitetsu_6050`` |
| 운영 속력(Speed) _(예시. ``300km/h``)_ | 110 km/h |
| 설계 최고 속력(Designed max. speed) _(예시. ``330km/h``)_ | 110 km/h |
| 화물 수송량(Capacity) _(예시. ``100명``)_ | ``선두차 132명`` ``중간차 146명`` |
| 출력(Power) _(예시. ``4400kW``)_ | ``6000형 1,080kW`` ``6050형 3량 990kw`` ``6050형 4량 1,155kw`` |
| 중량(Weight) _(예시. ``136t``)_ | ``선두차 29t`` ``6000형 중간차 38t`` ``6050형 중간차 36t`` |
| 도입연도(Introduction year) _(예시. ``2004``)_ | ``6000형 1993년`` ``6050형 1995년`` |

| 이름 | 조성 |
|--------|--------|
| 6000형 | ``3량 MC' - T - MC`` ``4량 TC - M - M' - TC`` |
| 6050형 | ``3량 TC - M' - TC`` ``4량 TC - M - M' - TC`` |

* 이 차량은 추후 올릴 니시테츠 7000형, 7050형과 병결운행이 가능합니다
* 같은 3량편성이라도 6050형은 VVVF 전동차여서 MT비가 다르며 중간객차의 무게를 가볍게 설정했습니다.

-----

* 니시테츠 7000형 / 7050형

| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) _(예시. ``KTX 산천``)_ | 니시테츠 7000/7050형 |
| 영문 이름(Name in English) _(예시. ``KTX Sancheon``)_ | Nishitetsu 7000/7050 series |
| 코드(Code) _(예시. ``KTX2N``)_ | ``Nishitetsu_7000`` ``Nishitetsu_7050`` |
| 운영 속력(Speed) _(예시. ``300km/h``)_ | 110 km/h |
| 설계 최고 속력(Designed max. speed) _(예시. ``330km/h``)_ | 120 km/h |
| 화물 수송량(Capacity) _(예시. ``100명``)_ | ``칸 당 130명`` ``편성 전체 260명`` |
| 출력(Power) _(예시. ``4400kW``)_ | 510kW |
| 중량(Weight) _(예시. ``136t``)_ | 30t |
| 도입연도(Introduction year) _(예시. ``2004``)_ | ``7000형 2000년`` ``7050형 2003년`` |

* 2량 1편성, MC' - TC 조성입니다
* 이전에 올린 6000형, 6050형과 병결운전이 가능합니다. ( https://youtu.be/afDCjcZBWaU )
* 7000형은 한쪽 면 출입문 4개, 7050형은 한쪽 면 출입문 3개입니다.

-----

* 니시테츠 8000형

| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) _(예시. ``KTX 산천``)_ | 니시테츠 8000형 |
| 영문 이름(Name in English) _(예시. ``KTX Sancheon``)_ | Nishitetsu 8000 series |
| 코드(Code) _(예시. ``KTX2N``)_ | ``Nishitetsu_8000`` |
| 운영 속력(Speed) _(예시. ``300km/h``)_ | 110 km/h |
| 설계 최고 속력(Designed max. speed) _(예시. ``330km/h``)_ | 110 km/h |
| 화물 수송량(Capacity) _(예시. ``100명``)_ | ``선두차 116명`` ``중간차 130명``  |
| 출력(Power) _(예시. ``4400kW``)_ | 2,160kW |
| 중량(Weight) _(예시. ``136t``)_ | ``선두차 29t`` ``중간차 36t`` |
| 도입연도(Introduction year) _(예시. ``2004``)_ | 1989 |

조성 ``TC - M - M' - M - M' - TC``

등장 당시부터 퇴역때까지 특급으로 운행하다 퇴역한 열차입니다.

-----

* 니시테츠 9000형

| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) _(예시. ``KTX 산천``)_ | 니시테츠 9000형 |
| 영문 이름(Name in English) _(예시. ``KTX Sancheon``)_ | Nishitetsu 9000 series |
| 코드(Code) _(예시. ``KTX2N``)_ | ``Nishitetsu_9000`` |
| 운영 속력(Speed) _(예시. ``300km/h``)_ | 110 km/h |
| 설계 최고 속력(Designed max. speed) _(예시. ``330km/h``)_ | 120 km/h |
| 화물 수송량(Capacity) _(예시. ``100명``)_ | ``선두차 124명`` ``중간차 138명``  |
| 출력(Power) _(예시. ``4400kW``)_ | 2,160kW |
| 중량(Weight) _(예시. ``136t``)_ | ``30t`` |
| 도입연도(Introduction year) _(예시. ``2004``)_ | 2016 |

3량편성: TC - M' - TC
2량편성: MC' - TC

**Comment by evepoi** [comment]
통합 작업으로 포함되었습니다.
