### ISSUE TITLE
[열차추가] [객차 고정편성 랜덤조성, 뒤집힘 방지 테스트] PEX(Premium EXpress)

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#266]
### 필수 스프라이트

![PEX_DTS](https://github.com/DTS-NewGRF/DTS/assets/88026704/3dc11f93-9752-40b2-a76b-55c80756f85e)

### 32bpp 스프라이트

해당 없음

### 실존 & 가상열차

- [X] 가상열차

### 편성방식

- [X] 고정편성

### 설명

객차 고정편성 및 뒤집힘 방지 테스트 용도 스프라이트입니다.

테스트 종료 후에는 DTS 오리지널 차량으로도 사용됩니다.

### GRF내 열차 이름 한국어

PEX(Premium EXpress)

### GRF내 열차 이름 영문

PEX(Premium EXpress)

### 열차속도

- [X] 일반열차 151 ~ 181km/h

### 도입년도

2022

### 전체 편성수

6량, 8량, 10량

### 객차당 수송량

각각 다름 **별도 표기**

### 편성구조

- 6량
  - 단층형: `N-N-N-B-N-N` **객차당 수송량 70명**

- 8량  
  - 단층형: `N-N-N-B-N-N-N-N` **객차당 수송량 70명**
    - 특실편성: `SN-N-N-B-N-N-N-N` **객차당 수송량 69명**
  - 심야형: `N-N-B-N-N-N-N-S` **객차당 수송량 64명**
    - 특실편성: `SN-N-B-N-N-N-N-S` **객차당 수송량 63명**

- 10량
  - 단층형: `N-N-N-N-N-B-N-N-N-N` **객차당 수송량 70명**
    - 특실편성: `SN-N-N-N-N-B-N-N-N-N` **객차당 수송량 69명**
  - 복합형: `N-N-N-N-N-B-N-N-N-DB` **객차당 수송량 84명**
    - 특실편성: `SN-N-N-N-N-B-N-N-N-DB` **객차당 수송량 76명**
  - 심야형: `N-N-N-N-N-B-N-N-N-S` **객차당 수송량 65명**
    - 특실편성: `SN-N-N-N-N-B-N-N-N-S` **객차당 수송량 65명**
  - 2층형: `DA-DA-DA-DA-DA-B-DA-DA-DA-DA` **객차당 수숭량 131명**
  - 2층형: `DA-DB-DA-DB-DA-B-DB-DA-DB-DA` **객차당 수숭량 131명**
  - 침대관광열차: `S-S-S-S-S-B-S-S-S-S` **객차당 수숭량 27명**

- 14량
  - 단층형: `N-N-N-N-N-N-B-N-N-N-N-N-N-N` **객차당 수송량 70명**
    - 특실편성: `SN-SN-N-N-N-N-B-N-N-N-N-N-N-N` **객차당 수송량 70명**
  - 복합형: `N-N-N-N-N-N-B-N-N-N-DA-DA-DA-DA` **객차당 수송량 90명**
    - 특실편성: `SN-SN-N-N-N-N-B-N-N-N-DA-DA-DA-DA` **객차당 수송량 89명**
  - 심야형: `N-N-N-N-N-N-B-DA-DA-DA-S-S-S-S` **객차당 수송량 68명** 
  - 침대관광열차: `S-S-S-S-S-S-B-S-S-S-S-S-S-S` **객차당 수숭량 26명**

- 18량
  - 단층형: `N-N-N-N-N-N-N-N-B-B-N-N-N-N-N-N-N-N` **객차당 수송량 70명**
    - 특실편성: `SN-SN-SN-N-N-N-N-N-B-B-N-N-N-N-N-N-N-N` **객차당 수송량 69명**

### 적용스팩 세부사항

- 수송량
  - N(일반실): 수송량 72명으로 산정
  - SN(특실): 수송량 68명으로 산정
  - D(2층차): 수송량 140명으로 산정
  - B(식당차): 수송량 50명으로 산정
  - S(침대차): 수송량 24명으로 산정

**Comment by evepoi** [comment]
본 이슈 열차 객차 자유편성으로 조정됩니다.
