### ISSUE TITLE
[열차변경] PEX 랜덤편성 적용 

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#267]
### 객화차 선택

[DTS] 관광열차

### 변경 스프라이트

![PEX_DTS](https://github.com/DTS-NewGRF/DTS/assets/88026704/6d72a5f6-7557-404c-85cf-79c36bd5dbe6)
- 구매창 이미지 수정(2층객차 그래픽이 수정 안되어있던 문제)
- N객차 도색구분

### 설명

N객차의 그래픽을 랜덤으로 섞은 편성을 지정하는 이슈입니다.

### 적용내용

랜덤편성 도색 추가

### 편성구조

랜덤 숫자 뽑기로 돌리면서 참고한 조합입니다. (3개씩만 넣었습니다. 순서는 임의로 바꾸셔도 됩니다.) 
- https://ohmyluck.com/ko/random-number/
`1 - A`, `2 - B`, `3 - C`

6량
- 단층형: `NB-NC-NC-B-NA-NA` `NB-NA-NA-B-NB-NC` `NC-NB-NC-B-NC-NA`

8량
- 단층형: `NA-NB-NB-B-NC-NA-NC-NC` `NB-NC-NB-B-NC-NA-NA-NB` `NB-NA-NB-B-NB-NC-NC-NA`
  - 특실편성: `SN-NA-NB-B-NB-NC-NA-NC` `SN-NA-NC-B-NC-NA-NB-NB`  `SN-NC-NC-B-NA-NB-NA-NB`
- 심야형: `NA-NA-B-NC-NC-NB-NB-S` `NC-NB-B-NC-NA-NB-NA-S` `NC-NC-B-NB-NA-NC-NA-S`
  - 특실편성: `SN-NA-B-NA-NB-NB-NC-S` `SN-NA-B-NA-NC-NB-NB-S` `SN-NB-B-NC-NA-NC-NA-S`

10량
- 단층형: `NC-NC-NB-NB-NA-B-NC-NA-NC-NB` `NB-NA-NA-NC-NA-B-NB-NB-NC-NB` `NA-NB-NC-NC-NA-B-NB-NA-NA-NC`
  - 특실편성: `SN-NB-NA-NB-NC-B-NB-NC-NA-NB` `SN-NA-NC-NA-NB-B-NB-NA-NC-NC` `SN-NC-NB-NC-NB-B-NB-NA-NA-NC`
- 복합형: `NA-NC-NB-NA-NC-B-NB-NB-NC-DB` `NC-NA-NA-NA-NB-B-NC-NA-NB-DB` `NC-NB-NB-NC-NC-B-NA-NA-NC-DB`
  - 특실편성: `SN-NA-NC-NA-NB-B-NC-NB-NC-DB` `SN-NB-NA-NA-NC-B-NA-NC-NA-DB` `SN-NC-NC-NB-NC-B-NA-NA-NB-DB`
- 심야형: `NC-NC-NB-NB-NA-B-NA-NB-NA-S` `NB-NA-NB-NC-NA-B-NC-NC-NA-S` `NB-NC-NC-NA-NA-B-NC-NB-NA-S`
  - 특실편성: `SN-NA-NA-NC-NB-B-NC-NB-NA-S`  `SN-NA-NC-NA-NB-B-NB-NC-NA-S` `SN-NA-NC-NC-NB-B-NB-NC-NA-S`
- 2층형: `DA-DB-DB-DA-DB-B-DA-DB-DB-DA` `DB-DA-DA-DA-DB-B-DB-DB-DA-DB`

14량
- 단층형: `NA-NB-NC-NA-NC-NA-B-NC-NC-NB-NB-NB-NC-NB` `NC-NC-NB-NC-NC-NA-B-NB-NA-NB-NA-NA-NA-NC` `NB-NB-NB-NC-NA-NB-B-NA-NC-NA-NA-NA-NC-NA`
  - 특실편성: `SN-SN-NC-NB-NB-NA-B-NB-NA-NC-NC-NC-NC-NA` `SN-SN-NA-NA-NC-NA-B-NC-NB-NA-NB-NB-NA-NC` `SN-SN-NB-NB-NC-NA-B-NA-NB-NA-NB-NC-NA-NC`
- 복합형: `NB-NA-NC-NA-NC-NB-B-NB-NA-NB-DA-DA-DA-DA` `NB-NC-NC-NA-NA-NB-B-NA-NC-NC-DA-DA-DA-DA` `NC-NC-NC-NA-NC-NB-BC-NC-NB-NA-DA-DA-DA-DA`
  - 특실편성: `SN-SN-NC-NC-NC-NB-B-NB-NA-NA-DA-DA-DA-DA` `SN-SN-NA-NC-NC-NA-B-NA-NB-NB-DA-DA-DA-DA` `SN-SN-NB-NC-NC-NC-B-NA-NA-NB-DA-DA-DA-DA`
- 심야형: `NC-NC-NA-NB-NB-NA-B-DA-DA-DA-S-S-S-S` `NC-NA-NA-NC-NB-NA-B-DA-DA-DA-S-S-S-S` `NB-NC-NA-NC-NB-NA-B-DA-DA-DA-S-S-S-S`

18량
- 단층형: `NB-NC-NB-NA-NC-NC-NA-NA-B-B-NB-NC-NA-NA-NC-NA-NC-NA` `NA-NA-NB-NC-NB-NA-NA-NA-B-B-NB-NB-NA-NB-NC-NC-NB-NB` `NB-NA-NB-NB-NA-NB-NB-NA-B-B-NC-NA-NB-NC-NC-NA-NB-NC`
  - 특실편성: `SN-SN-SN-NB-NA-NB-NB-NA-B-B-NC-NC-NC-NB-NB-NA-NA-NA` `SN-SN-SN-NC-NB-NB-NA-NC-B-B-NA-NB-NC-NA-NB-NB-NC-NA` `SN-SN-SN-NC-NA-NC-NB-NC-B-B-NC-NA-NB-NB-NB-NB-NC-NB`

**Comment by evepoi** [comment]
PEX 객차 자유편성세팅으로 본 이슈 닫습니다.
