### ISSUE TITLE
[열차추가] 케이세이 3500형

### ISSUE THREAD

**Issue by kimjostars** [DTS-NewGRF/DTS#28]
==========[필수스프라이트]==========
![케이세이-3500](https://github.com/DTS-NewGRF/DTS/assets/110330835/9b5b1a70-bf86-4c16-b15e-bc1a575cb397)

==========[설명]==========
TIAS (Toei Interlocking Add-on Set)의 케이세이 3500형을 DTS규격으로 변경한 스프라이트

차량구성 예시:
(4량)TM1-'M-'M-TM2
(6량)TM1-T-'M-'M-T-TM2

==========[기본GRF]==========
베이스 : TIAS (Toei Interlocking Add-on Set)
도색 : 현도색

==========[적용스팩]==========
GRF내 열차 이름 : 케이세이 3500형
열차속도 :120KM/h
도입년도 : 1972년
실존여부 : O

**Comment by JukjeonWani** [comment]
스프라이트 규격 안맞습니다

**Comment by kimjostars** [comment]
수정
![케이세이-3500](https://github.com/DTS-NewGRF/DTS/assets/110330835/60d1ea95-be5a-40f3-b1fc-e753e7334a20)
T칸추가 차량구매창에서의 모습도 추가

**Comment by kimjostars** [comment]
최종본
![케이세이-3500](https://github.com/DTS-NewGRF/DTS/assets/110330835/8b1e61b8-287c-4f73-875b-76296f769241)
스프라이트 일부변경

**Comment by kimjostars** [comment]
TM1,TM2를 Mc1,Mc2로 변경

**Comment by evepoi** [comment]
당분간 보류 이슈 닫으니 공개 시점에 본 이슈 오픈해주세요.
