### ISSUE TITLE
[열차추가] EMU-150 2층객차 추가 2CC

### ISSUE THREAD

**Issue by kimjostars** [DTS-NewGRF/DTS#29]
==========[필수스프라이트]==========
![EMU150 2L](https://github.com/DTS-NewGRF/DTS/assets/110330835/ec4410d8-7163-4bb0-be08-8bf89d63a3c5)

==========[설명]==========
EMU-150 6량 1층객차에 2층객차 2량추가버전
==========[기본GRF]==========
베이스 : KR+
도색 : 2CC

==========[적용스팩]==========
GRF내 열차 이름 : EMU150 2층객차포함
열차속도 :기본EMU150과 동일
도입년도 : EMU150과 동일
객차당 수송량 : EMU150과 동일
최소 편성수 : EMU150과 동일
실존여부 : X

**Comment by JukjeonWani** [comment]
* 승객 수송량: 98명
* 8량 열차에만 편성
* 4, 5호차에 편성
