### ISSUE TITLE
[건물추가] 차량기지 회사색상 4방향 

### ISSUE THREAD

**Issue by Pokerface-YUTHMAIN** [DTS-NewGRF/DTS#291]
### 필수 스프라이트

![Trainhouse 2CC 4](https://github.com/DTS-NewGRF/DTS/assets/101701121/8abd8c74-4ca0-40ab-844e-5e4bca3665d2)

### 설명

회사색상 4방향 차량기지 건물 스프라이트입니다. 

### GRF내 열차 이름 한국어

차량기지 

### GRF내 열차 이름 영문

Vehicle Depot

**Comment by evepoi** [comment]
본 이슈는 선로셋과 함께 적용이 되어야 하는 부분으로. 일시적으로 잠시 보류하겠습니다.
