### ISSUE TITLE
[버그] 일부 열차의 사운드 적용이 잘못되어 있음

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#298]
- [x] 서울교통공사 4000호대 1세대: IGBT 사운드에서 GTO 사운드가 나옴(MITSUBISHIGTOKstart → DAWONSYSIGBTstart 변경 필요)
- [x] 한국철도공사 2세대 VVVF 전동차: 311K IGBT 에서 GTO 사운드가 나옴

**Comment by evepoi** [comment]
코딩 내용수치 오류로 버그 확인됨.
