### ISSUE TITLE
[열차변경] 8600호대 전기기관차 싱글암버전 팬터그래프 일부수정

### ISSUE THREAD

**Issue by kimjostars** [DTS-NewGRF/DTS#30]
==========[필수스프라이트]==========
![EL-8600 싱글암](https://github.com/DTS-NewGRF/DTS/assets/110330835/26b9b305-288f-458c-9277-d35aa1f122f2)

**Comment by evepoi** [comment]
깃허브 기존 자료를 바탕으로 제작하지 않았기에 보류합니다
