### ISSUE TITLE
[열차변경] 수익

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#321]
### 기본 열차 선택

사운드가 적용된 **모든 차량**

### 변경 스프라이트

https://github.com/OpenTTD/OpenSFX/tree/master/src
wav → osfx_20

### 설명

수익이 발생하면 나오는 게임 내 기본 효과음입니다.

### 적용내용

- [x] `SOUND_EVENT_LOAD_UNLOAD` 사운드 지정: `osfx_20`

### 편성구조

해당 없음

**Comment by evepoi** [comment]
우선적으로 7X00호대 디젤기관차에만 적용했습니다.

**Comment by JukjeonWani** [comment]
@evepoi 사운드 적용된 모든 차량에 전부 적용해도 될 것 같습니다.
