### ISSUE TITLE
[버그] 수도권 1호선 저항제어 전동차 [초기저항] 철도청 구도색 그래픽 오류

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#339]
### 버그사항

![image](https://github.com/DTS-NewGRF/DTS/assets/88026704/113f5da6-40c1-4637-b192-ee8815ba4c59)

### 개선점

일부 그래픽의 탬플릿 정렬이 어긋나 있는 상태라서 수정하였습니다.
![RHIO_1_K1000_OLD](https://github.com/DTS-NewGRF/DTS/assets/88026704/3134b68b-078e-4cf7-b22b-35b0ebee8bd8)

**Comment by evepoi** [comment]
코레일 열차 그룹 통합하면서 작업하겠습니다.
