### ISSUE TITLE
[버그]  TGV 도색변경후 복제시 선두기관차만 도색이 복제됨

### ISSUE THREAD

**Issue by kimjostars** [DTS-NewGRF/DTS#37]
==========[버그내용]==========
도색변경후 복제시 선두기관차만 도색이 복제됨
==========[DTS내용]==========
DTS 열차 이름 : TGV쉬드-에스트

**Comment by JukjeonWani** [comment]
고정편성 작업되면 자연스럽게 해결될 버그입니다.

**Comment by evepoi** [comment]
네 바로 그부분 때문에 고정편성으로 전환하고 있습니다.
아직 TGV를 비롯해 일부는 작업이 되지 않았습니다.

구매목록상 [?량] 열차이름 [DTS]가 작업이 완료된 사항입니다.
그외는 아직 미작업상태입니다.

감사합니다.
