### ISSUE TITLE
[스프라이트] 열차 전시장

### ISSUE THREAD

**Issue by Pokerface-YUTHMAIN** [DTS-NewGRF/DTS#375]
### 32bpp 스프라이트

![전시장](https://github.com/DTS-NewGRF/DTS/assets/101701121/88fb153c-1c6d-4da9-866d-6a50b3a2dbd5)

5*1 사이즈입니다.

**Comment by evepoi** [comment]
현 상황으로는 해결점이 없으므로 보류합니다.
