### ISSUE TITLE
[열차추가] 한-아세안 열차(ASEAN Korea Train)

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#428]
### 필수 스프라이트

![ASEAN Korea Train](https://github.com/DTS-NewGRF/DTS/assets/88026704/9b3778fd-7b15-4664-841a-c7645cd211fb)

### 32bpp 스프라이트

해당 없음

### 실존 & 가상열차

- [X] 실존차량

### 편성방식

- [X] 고정편성

### 설명

2019년 10월 16일부터 10월 18일까지 3일간 운행한 특별열차입니다.
2019년 11월 한-아세안 정상회담의 성공적인 개최를 위해 운행되었다고 하며, 서울 - 영천 - 부산 - 순천 - 서울 순으로 운행되었다고 합니다.

ref.
- https://cafe.naver.com/korailslr/91142
- https://blog.naver.com/kimhr91/221680715125
- https://cafe.naver.com/korailslr/91139
- https://cafe.naver.com/korailslr/91127
- https://blog.naver.com/by_december/221680089345
- https://youtu.be/rsgl2-J_MFA?si=iFL34y8i6ceRgbH6

### GRF내 열차 이름 한국어

한-아세안열차

### GRF내 열차 이름 영문

ASEAN Korea Train

### 열차속도

- [X] 일반열차 151 ~ 181km/h

### 도입년도

2019

### 전체 편성수

7량

### 객차당 수송량

72명

### 편성구조

**1번부터 7번까지 순서대로**

### 적용스팩 세부사항

**관광열차 그룹에 넣으시면 됩니다.**
임시로 칠해지는 특별도색이라 기존 도색이 남아있습니다.
(이는 디젤기관차와 1호차 객실에 해당)
1호차 객차는 리미트 격상 새마을호 객차에 특별도색을 입힌 경우로 측면에만 랩핑이 되어있었습니다.
2~7호차와 발전차는 충북영동국악와인열차 편성을 그대로 활용하였습니다.

**Comment by evepoi** [comment]
적용 : 1번그래픽만 적용하고, 2~7번은 충북영동국악와인열차 그래픽의 주소와 위치를 그대로 따왔습니다.
향후 새로운 도색이 나오지 않는 이상, 2~7번은 충북영동국악와인열차의 그래픽에 귀속됩니다.
