### ISSUE TITLE
[열차변경][도색추가] KTX-청롱 DD 도색 추가

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#429]
### 변경 스프라이트

- 8bpp
https://github.com/DTS-NewGRF/DTS/issues/415#issue-2215052330 해당 그래픽으로 대체
 
- 32bpp
![KTX-CR DD_32bpp](https://github.com/DTS-NewGRF/DTS/assets/88026704/9bf4c2bd-79f0-42a9-b8e7-340390e6a022)

- 회사색상 오버레이
![KTX-CR DD_32bpp_Company Layer](https://github.com/DTS-NewGRF/DTS/assets/88026704/a1467ad9-c235-4bfb-b002-3fb3f6856b9b)

### 설명

KTX-청룡 DD 도색 추가입니다.
`KTX-청룡` 도색

### 적용내용

도색 추가

### 편성구조

변동 없음
`TC1-M1-M2-M3-M2-M2(1)-M4-TC2`

**Comment by evepoi** [comment]
기본도색으로 변경.
