### ISSUE TITLE
[열차추가] 의정부경전철 2CC

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#468]
### 필수 스프라이트

![Uijeongbu_AGT](https://github.com/DTS-NewGRF/DTS/assets/88026704/036f397f-2560-4fab-80bd-b4381b200a8e)

### 32bpp 스프라이트

없음

### 실존 & 가상열차

- [X] 실존차량

### 편성방식

- [X] 고정편성

### 설명

의정부경전철에 운행중인 고무차륜경전철입니다.
2량 1편성입니다.

**그래픽 길이 7입니다.**
선로코드 **`LAGT`로 지정**

ref
- https://www.ulrt.co.kr/trains
- https://blog.naver.com/cans3252/222562923576
- https://blog.naver.com/1503pjh/220483207657
- https://youtu.be/e4j_qhL_JFo?si=Yx8kM9gdO1poCW52

### GRF내 열차 이름 한국어

의정부 경전철

### GRF내 열차 이름 영문

Uijeongbu Light Rapid Transit

### 열차속도

- [X] 지하철/통근열차 100 ~ 151km/h

### 도입년도

2011

### 전체 편성수

2량

### 객차당 수송량

118명

### 편성구조

`MC - MC`

### 적용스팩 세부사항

- 최고속도: 80km/h
- 편성 출력: 500kw

**출발 사운드 추가**
- [x] Siemens_IGBT_CHOPPER_start

**Comment by evepoi** [comment]
그래픽 보류로 상황에 맞게 수정하였습니다.
