### ISSUE TITLE
[버그] 와인인삼트레인 3호차 그래픽 문제

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#482]
### 버그사항

![image](https://github.com/DTS-NewGRF/DTS/assets/88026704/f1da9d79-bb6e-45ac-bfcb-51cb56df789b)

### 개선점

해당 차량은 32bpp로 작업된 객차입니다.
하지만 다른 차량은 8bpp 그래픽으로 작업되어 있습니다.

32bpp 그래픽에는 구매창 이미지 영역이 생략되어 있는데 이것을 기본 그래픽으로 바꾸면서 그래픽 위치가 달라져 생긴 문제로 추측됩니다.

**Comment by evepoi** [comment]
위치 조정이 잘못세팅되어 긴급 수정했습니다.
