### ISSUE TITLE
[열차변경] 한-아세안열차 그래픽 변경

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#484]
### 변경 스프라이트

![wine_passinger Asean_32bpp](https://github.com/DTS-NewGRF/DTS/assets/88026704/9d6baebd-df15-4e1b-8bd5-5aef020caa0e)

### 설명

2호차부터 7호차까지 고증오류 수정

### 적용내용

그래픽 변경

### 편성구조

변동 없음

**Comment by evepoi** [comment]
코딩상 한-아세한 1량의 그래픽만 적용되고 나머지는 뒤 충북영동국악열차의 그래픽에 귀속되어 적용되어 있습니다.
다음 작업시 첫번째 1번 객차만 적용해주셔도 됩니다.

**Comment by JukjeonWani** [comment]
@evepoi 
충북영동국악와인열차와 한-아세안 열차는 출입문쪽 그래픽이 약간 다르며, 이번 고증오류 수정을 통해 같이 수정하기 위해 7량 전체가 작업되었습니다.

2~7호차의 부분이 충북영동국악와인열차에 귀속되지 않고 따로 작업되는 것을 의도하고 작업한 그래픽입니다.
