### ISSUE TITLE
[버그] 정선아리랑 유람열차 그래픽 문제

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#486]
### 버그사항

![image](https://github.com/DTS-NewGRF/DTS/assets/88026704/b0514e46-e312-4142-b119-89666dbbfb60)
![image](https://github.com/DTS-NewGRF/DTS/assets/88026704/a685a4cd-03ec-4b39-a540-f8532f795f55)
![image](https://github.com/DTS-NewGRF/DTS/assets/88026704/82a99673-b5c8-4d3d-b88b-f356a803af21)
![image](https://github.com/DTS-NewGRF/DTS/assets/88026704/a7a25e12-9f97-498f-91e2-e335b0f48c96)

#482 와 동일증상으로 추정됨

### 개선점

해당 차량은 8bpp로 작업된 객차입니다.
32bpp로 수정하며 신도색 부분의 그래픽 위치가 달라져 문제가 발생한 것으로 보입니다.

기존에 작업된 8bpp그래픽은 구색과 신도색의 표기로 인해 다른 차량과 그래픽 위치가 다릅니다.
32bpp가 적용되며 구도색의 그래픽 위치는 수정되었는데 신도색의 그래픽 위치가 교정되지 않은 듯 합니다.

**Comment by evepoi** [comment]
긴급 버그로 1.49릴리즈로 수정합니다.
