### ISSUE TITLE
[버그] 기존선 선로에서 철차륜 3궤조 경전철 차량이 나오는 현상

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#537]
### 버그사항

![image](https://github.com/user-attachments/assets/8d956c2f-9c92-48c6-bb34-9d3fa6d8655d)

### 개선점

철차륜 3궤조 경전철 차량 선로코드 지정이 잘못된 것으로 보임

부산김해경전철, 동북선, 김포골드라인, 인천교통공사 2000호대, 우이신설선, 자카르타 LRT: 선로코드 지정을 `RAIL` 에서 `3RDR`로 수정

**Comment by evepoi** [comment]
DTS-선로셋의 코드내용 수정으로 해결.
