### ISSUE TITLE
[열차추가] 디젤액압동차 초기도색 (32bpp)

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#559]
### 스프라이트

![Diesel Car_Original](https://github.com/user-attachments/assets/00451378-0613-4688-9389-d75bea4ad283)

### 실존 & 가상열차

- [X] 실존차량

### 편성방식

- [X] 고정편성
- [X] 단일구성 (객화차 & 단일 기관차)

### 설명

1961년부터 1975년까지 도입된 단량 디젤동차입니다. 일부 차량은 편운전대 방식으로 2량 이상의 편성에 사용되었습니다.
편운전대 차량은 그래픽 이름과 달리 **1966년 생산**되었습니다.
중간에 비둘기호 객차를 끼워넣어 운행하기도 했습니다.

ref.
- https://namu.wiki/w/DC%20%EB%94%94%EC%A0%A4%EB%8F%99%EC%B0%A8
- https://youtu.be/GvG1prNmHQw?si=XyxCDJy3gkaZH03s

### GRF내 열차 이름 한국어

디제액압동차

### GRF내 열차 이름 영문

Diesel Car

### 열차속도

- [X] 지하철/통근열차 100 ~ 151km/h

### 도입년도

1961

### 전체 편성수

단량 / 2량

### 객차당 수송량

1961년 생산: 126명 / 1966년 생산: 132명 / 1975년 생산: 174명 / 2량편성: 별도표기

### 편성구조

- 단량: 1961, 1966, 1975
- 2량 이상: 
  - `1966 + (DUMMY)1975_1(1966)`**객차당 수송량 132명** (등장년도 1966)
  - `1975_1(1966) + 1966`**객차당 수송량 132명** (등장년도 1966)
  - `1966 + (DUMMY)1975_1`**객차당 수송량 153명** (등장년도 1975)
  - `1975_1 + 1966`**객차당 수송량 153명** (등장년도 1975)
  - `1975_1 + (DUMMY)1975_1`**객차당 수송량 174명** (등장년도 1975)
  - 중간에 비둘기호 객차 및 동력차를 연결해 운행한 경우가 존재함

### 적용스팩 세부사항

**도색 이름**
- 1961: 초기형 초기도색 (1st Original livery)
- 1966: 후기형 초기도색 (2nd Original livery)
- 1975_1: 후기형 편운전대 초기도색 세미크로스시트 (2nd Single Cab Original livery Semi cross seat) **1966년 등장**
- 1975_1: 후기형 편운전대 초기도색 롱시트 (2nd Single Cab Original livery Long seat) **1975년 등장**

**차량 성능**
최고속도: 100km/h
힘: 269kw
무게: 50t

**출발 사운드**
- [x] Old_DMU_start

**정지 사운드`SOUND_EVENT_STOPPED`**
- [x] Old_DMU_idle

**수익 사운드**
- [x] 기본 효과음(osfx_20)

**Comment by evepoi** [comment]
제작 특성상 2량의 편성은 보류하도록 하고 단량구성만으로 자율적인 편성이 되도록 세팅하고 마무리하겠습니다.
