### ISSUE TITLE
[열차변경][도색추가] 디젤액압동차 철도청도색 (8bpp_회사 색상)

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#560]
### 변경 스프라이트

![Diesel Car_KNR_OLD](https://github.com/user-attachments/assets/52e035a4-132b-4616-a213-2b04ad65e1cf)

### 깃허브 자료실 파일명

해당 없음_추가 예정 차량

### 설명

디젤액압동차의 비둘기호 및 보급열차, 통일호, 무궁화호 격상 도색입니다.

통일호 격상 차량과 무궁화호 격상 차량은 수송량이 다릅니다.
(양운전대 수송량: 64명, 편운전대 수송량: 84명)
또한, 무궁화호 격상 차량은 냉방개조가 되어 있다는 특징이 있습니다.

| 도색 이름 (한글) | 도색 이름 (영문) |그래픽 코드 | 등장년도 | (1량) 수송량 | 
|-----|-----|-----|-----|-----|
| 보급열차 양운전대 | regular express train Double Cab | `1974_O` | 1980 | 132명 |
| 보급열차 편운전대 | regular express train Single Cab | `1974_O1` | 1980 | 132명 |
| 비둘기호 초기형 | Bidulgi 1st | `1980_B1` | 1984 | 126명 |
| 비둘기호 후기형 | Bidulgi 2nd | `1980_B2` | 1984 | 132명 |
| 비둘기호 편운전대 세미크로스시트 | Bidulgi Single Cab Semi cross seat | `1984_B` | 1980 | 132명 |
| 비둘기호 편운전대 롱시트 | Bidulgi Single Cab Long seat | `1984_B` | 1980 | 174명 |
| 통일호 양운전대 | Tongil Double Cab | `1985_T` | 1985 | 64명 |
| 통일호 편운전대 | Tongil Singie Cab | `1985_T1` | 1985 | 84명 |
| 무궁화호 양운전대 | Mugunghwa Double Cab | `1985_M` | 1985 | 64명 |
| 무궁화호 편운전대 | Mugunghwa Singie Cab | `1985_M1` | 1985 | 84명 |

ref.
- https://namu.wiki/w/DC%20%EB%94%94%EC%A0%A4%EB%8F%99%EC%B0%A8#s-3.3
- https://namu.wiki/w/%EA%B4%91%EC%9A%B4%EB%8C%80%EC%97%AD#s-2
- 한국철도차량 100년사 1장

### 적용내용

도색 추가

### 편성구조

모든 도색은 단량도색으로 포함됩니다.
- 2량 이상(비둘기호): `1980_B2 + (DUMMY) 1980_B`**객차당 수송량 153명**, `1980_B + 1980_B2`**객차당 수송량 153명**, `1980_B + (DUMMY) 1980_B`**객차당 수송량 174명**
- 2량 이상(보급열차): `1980_O + (DUMMY) 1980_O1`**객차당 수송량 153명**, `1980_O1 + 1980_O`**객차당 수송량 153명**, `1980_O1 + (DUMMY) 1980_O1`**객차당 수송량 174명**
- 2량 이상 (통일호): `1985_T + (DUMMY) 1985_T1`**객차당 수송량 74명**, `1985_T1 + 1985_T`**객차당 수송량 74명**, `1985_T1 + (DUMMY) 1985_T1`**객차당 수송량 84명**
- 2량 이상 (무궁화호): `1985_M + (DUMMY) 1985_M1`**객차당 수송량 74명**, `1985_M1 + 1985_M`**객차당 수송량 74명**, `1985_M1 + (DUMMY) 1985_M1`**객차당 수송량 84명**

**Comment by evepoi** [comment]
2량 세팅은 적용하지 않고 단량으로 추가합니다.
