### ISSUE TITLE
[버그] 무궁화호 서비스 객차 일부가 최고속도 120km/h인 현상

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#571]
### 버그사항

![image](https://github.com/user-attachments/assets/7356264c-5cdc-406b-99de-fdcca97251f1)
해당 도색은 최고속도 150km/h이나 최고속도 120km/h로 되어 있음

### 깃허브 자료실 파일명

#354, #360 참고
`(2003) SDC`, `NPG`, `NCAFE`, `NSMF`, `NNC`, `ORC`, `NRC`, `(2014) NRS`

### 개선점

최고속도 150km/h로 수정

**Comment by evepoi** [comment]
수정 작업중 예상치 못한 오류버그로 해당열차 서비스차량에 대해서 속도제한을 완전 제거하는 것으로 결정함.
