### ISSUE TITLE
[열차변경] 7×00호대 디젤기관차 2CC, 회사 색상 도색 수정

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#60]
==========[필수스프라이트]==========
![image](https://github.com/DTS-NewGRF/DTS/assets/88026704/61412d77-e022-4656-baa8-0de0c7fc2d61)

==========[설명]==========
마찬가지로 기존 색상이 밝게 나와서 수정한 스프라이트입니다.

==========[적용내용]==========
적용될 기존 열차 이름: 7×00호대 디젤기관차
도색 추가시 열차 이름: 현도색 객화겸용, 구도색, 초기도색 화물, 초기도색 여객. 현도색 화물

**Comment by evepoi** [comment]
이미 올려진 이미지에는 열차 종류가 많이 있습니다. 깃허브 자료를 바탕으로 작업부탁드립니다.

**Comment by JukjeonWani** [comment]
@evepoi 
![GT26CW_Company_All](https://github.com/DTS-NewGRF/DTS/assets/88026704/056bf371-aaad-4d18-a907-5586cf96600c)
본 이슈 스프라이트는 src/locomotive/GT26CW/GT26CW.png 위에 수정한 그래픽입니다. 혹시 몰라 전체 스프라이트 올려드립니다.

**Comment by evepoi** [comment]
감사합니다. 이렇게 작업되어야 제가 기존 남겨야할 자료까지 날리지 일이 없습니다. ㅠㅠ
