### ISSUE TITLE
[열차변경] 한큐전철 6000계 스프라이트 오류

### ISSUE THREAD

**Issue by kimjostars** [DTS-NewGRF/DTS#78]
==========[필수스프라이트]==========
![Hankyu-6000](https://github.com/DTS-NewGRF/DTS/assets/110330835/f8c6c805-63f2-4b02-b88e-011b999274e7)

==========[설명]==========
기존 스프라이트의 선두차량 전두부에서 우측 창문이 빠져있던문제

**Comment by evepoi** [comment]
몇몇 스프라이트의 정렬이 안맞습니다.
본 자료는 이미 깃허브에 업로드 된 열차로 깃허브 자료 바탕으로 작업해달라고 말씀드렸는데, 고스란히 무시됬네요.

이런경우가 반복될경우, 강제 보류, 이슈닫겠습니다. 유념해주세요ㅠㅠ

**Comment by evepoi** [comment]
이번 작업승인이 마지막이오니 유념해주세요.
