### ISSUE TITLE
[열차추가] EMU-150 회사도색 추가

### ISSUE THREAD

**Issue by kimjostars** [DTS-NewGRF/DTS#8]
==========[필수스프라이트]==========
![EMU-150_company](https://github.com/DTS-NewGRF/DTS/assets/110330835/fb23100c-2a5b-4395-b3a6-ef91732ed304)
기본스프라이트

==========[설명]==========
EMU150을 기반으로 하여 회사도색을 적용한 열차 입니다.
==========[기본GRF]==========
베이스 : KR+
도색 : EMU-150

==========[적용스팩]==========
GRF내 열차 이름 : EMU-150 회사도색/EMU-150 company
열차속도 :165km/h
도입년도 : 2022년
객차당 수송량 : 기본 EMU-150과 동일
최소 편성수 : 4량
실존여부 : X

===========[편성 조성 방법]==========
4량:TC1-M'1-M'2-TC2
5량:TC1-M'1-M,T-M'2-TC2
6량:TC1-M'1-M,T-M,T-M'2-TC2
6량이후 짝수량 편성:TC1-M'1-M,T-M,T-M'2-TC2 (M'1,2-M,T-M,T 5호차부터 반복)
7량이후 홀수량 편성:TC1-M'1-M,T-M,T-M,T-M'2-TC2 (M'1,2-M,T-M,T-M,T 6호차부터 반복)

**Comment by JukjeonWani** [comment]
이거 32bpp라 작업 보류였던 열차로 아는데 문제 해결된건가요?

**Comment by evepoi** [comment]
당시 열차폴더 위치 착각으로 추후 작업예정이였습니다.
이번 개선이 작업해두겠습니다
