### ISSUE TITLE
[열차추가] 성신RST 2000년식 MSB 모터카

### ISSUE THREAD

**Issue by littmannkim** [DTS-NewGRF/DTS#82]
==========[필수스프라이트]==========
![Z1FINAL2](https://github.com/DTS-NewGRF/DTS/assets/80151658/f14ac41b-623a-4f3f-97ae-5b4088a38691)

==========[Alternative 스프라이트]==========
![MSB ZL2](https://github.com/DTS-NewGRF/DTS/assets/80151658/a2b47744-ef21-469f-9634-73a70bba8ba9)

==========[설명]==========
한국철도공사 MSB 모터카입니다. 

==========[적용스팩]==========
GRF내 열차 이름 : MSB 모터카/ MSB Speeder
열차속도 : 80km/h
열차 견인력: 475hp
열차 무게: 25t
도입년도 : 2000년
객차당 수송량 : 9명
tractive_effort_coefficient:  0.25
air_drag_coefficient:  0.06
실존여부 :  실존

**Comment by littmannkim** [comment]
> Alternative 스프라이트 몇배인가요?

4배입니다.

**Comment by evepoi** [comment]
TTD 팔레트를 사용하지 않으셨네요. 일단 첫 차량이니 어느 정도 세팅은 해보겠습니다.
스프라이트 수정은 공개된 이후 보시고 수정하시면 될것으로 보여집니다.
