### ISSUE TITLE
[열차변경] 한큐 6000계 스프라이트 수정

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#83]
==========[필수스프라이트]==========
![HANKYU_6000](https://github.com/DTS-NewGRF/DTS/assets/88026704/36b2a4ca-6ae9-423c-a909-b13988a12bef)

==========[설명]==========
공조기 스프라이트를 좀 더 현실적으로 보이게 수정한 스프라이트입니다.

==========[적용내용]==========
적용될 기존 열차 이름: 한큐 6000계

**Comment by JukjeonWani** [comment]
@kimjostars
6300계 포함 한큐전철 스프라이트는 이 스프라이트를 기준으로 작업해주시기 바랍니다.

**Comment by kimjostars** [comment]
> @kimjostars 6300계를 포함하는 한큐전철 게이지 라이트는 이 기준 라이트를 기준으로 작업하시기 바랍니다.

확인
