### ISSUE TITLE
[버그] GTX 편성 문제

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS#9]
==========[버그내용]==========
![image](https://github.com/DTS-NewGRF/DTS/assets/88026704/588e8270-8e23-4d0a-bd2f-f82c31e8d174)
현재 조성(8량 기준): TC-M'-M-T-T-M-M'-TC

==========[개선사항]==========
실제 조성(8량 기준): TC-M-T'-M-M-T'-M-TC
팬터그래프 객차의 위치가 8량 기준 3, 6호차에 위치해야함

```
4량: TC-T'-T'-TC
5량: TC-T'-M-T'-TC
6량: TC-T'-M-M-T'-TC
7량: TC-T'-M-M-T'-M-TC
8량: TC-M-T'-M-M-T'-M-TC
8량 초과: TC-M-T'-M-...-M-T'-M-TC
```

==========[YST내용]==========
DTS 열차 이름 : GTX

**Comment by evepoi** [comment]
관련된 사항은 객차별 수동편성으로 자연스럽게 해결될 부분입니다.
