### ISSUE TITLE
[열차추가] 한큐전철 8000, 8300계

### ISSUE THREAD

**Issue by kimjostars** [DTS-NewGRF/DTS#92]
==========[필수스프라이트]==========
![Hankyu-8000,8300](https://github.com/DTS-NewGRF/DTS/assets/110330835/14602e04-eb66-44a6-a186-dba89859bd5a)

==========[설명]==========
한큐전철의 8000,8300계 차량입니다.

========[적용스팩]============
GRF내 열차 이름 : 한큐전철 8000,8300계/Hankyu 8000,8300series
열차속도 :120km/h
도입년도 : 1989년
객차당 수송량 : 롱시트(기본)선두,후두차:132명
                          롱시트(기본)중간차:142명
                          크로스시트(개조시)선두,후두차:126명
                          크로스시트(개조시)중간차:137명
최소 편성수 : 2량
실존여부 : O
개조시 롱시트을 기본으로 크로스시트로 개조가 가능하게 해주십쇼
========[편성구성]============
2량:
<-뒤 앞->
Mc - Mc'

8량
<-뒤 앞->
Mc - M,T' - M,T - M,T - M,T - M,T - M,T - Mc'

**Comment by JukjeonWani** [comment]
따로 분리해서 추가해주세요
8000계: 도시바 GTO
8300계: 도요전기제 GTO

**Comment by evepoi** [comment]
지금의 고정편성시에는 수송량이 변화되지 않습니다.
특별한 명시가 없는한 기본 수송량에 맞춰 작업하겠습니다.
